### ISSUE TITLE
Peer-to-Peer Programming

### ISSUE THREAD

**Issue by DuaneDave** [barakadanny/code-review#2]
### **Peer-to-Peer Review** 

  here we are to review @barakadanny code

**Comment by DuaneDave** [comment]
Hi @barakadanny 👋 

Great job so far on your project 💯 , I must say that the code presentation is perfect and clean, however, there are some changes we feel if implemented will overall make this repo even more professional. 

  - The branch naming convention could be a bit more descriptive
  - The commit messages are a bit too long and since you are fixing the same issue, I suggest a shorter 
     name like "Linter error fix" wouldn't be bad

Cheers and happy coding 👏

**Comment by barakadanny** [comment]
Thank you for the feedback, 
I will work on them.
